[project]
name = "multiagentsnewsletter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "elevenlabs>=2.6.0",
    "firecrawl-py>=2.15.0",
    "openai-agents>=0.1.0",
]
